#!/bin/bash
echo "🚀 MongoDB Atlas Quick Setup Guide"
echo ""
echo "Since local MongoDB isn't working, let's use MongoDB Atlas (Cloud):"
echo ""
echo "1. Go to: https://www.mongodb.com/cloud/atlas/register"
echo "2. Sign up for free account"
echo "3. Create a FREE cluster"
echo "4. Create database user (username: shield360)"
echo "5. Whitelist IP (Allow from anywhere)"
echo "6. Get connection string from 'Connect' button"
echo "7. Update shield360-backend/.env with the connection string"
echo ""
echo "Connection string format:"
echo "MONGODB_URI=mongodb+srv://shield360:PASSWORD@cluster0.xxxxx.mongodb.net/shield360?retryWrites=true&w=majority"
echo ""
echo "Then run: cd shield360-backend && npm run check-db"
echo ""
echo "Detailed guide: See SETUP_MONGODB_ATLAS.md"
